workflows:
  build-android-debug:
    name: Build Android Debug APK
    max_build_duration: 30
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
