workflows:
  build-android-debug:
    name: Build Android Debug APK
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build APK (debug)
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
    publishing:
      email:
        recipients:
          - your@email.com
